# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'package-lock.json'
    path: 'node_modules'
    cacheHitVar: 'CacheRestored'

- script: npm install
  displayName: npm install
  condition: ne(variables['CacheRestored'], 'true')

- script: npm run build
  displayName: 'npm build'
